FROM ubuntu:24.04 AS base

ARG DEPS_SOURCE_DIR="/sources"
ARG CLANG_VERSION="18"
ARG CATCH2_VERSION="3.8.0"
ARG CPPTRACE_VERSION="0.7.5"
ARG FMT_VERSION="11.1.3"
ARG MAGIC_ENUM_VERSION="0.9.7"
ARG BOX2D_VERSION="2.4.2"
ARG ENTT_VERSION="3.14.0"
ARG GLFW_VERSION="3.4"
ARG GLM_VERSION="release-1.0.2"
ARG GLSLANG_VERSION="15.1.0"
ARG IMGUI_VERSION="docking"
ARG ZLIB_VERSION="1.3.1"
ARG PNG_VERSION="1.6.46"
ARG FREETYPE_VERSION="VER-2-13-3"
ARG TINYXML2_VERSION="10.0.0"
ARG MSDF_ATLAS_GEN_VERSION="1.3"
ARG STB_VERSION="master"
ARG LLVM_MINGW_TOOLCHAIN_URI="20250114/llvm-mingw-20250114-ucrt-ubuntu-20.04-x86_64.tar.xz"
ARG INSTALL_DIR="/out"

# -------------------------------------------------------------------------------------------------
# Install build tools
# -------------------------------------------------------------------------------------------------

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
    ninja-build \
    cmake \
    pkg-config \
    wget \
    xz-utils \
    git \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ENV CMAKE_GENERATOR="Ninja"

# -------------------------------------------------------------------------------------------------
# Install toolchain
# -------------------------------------------------------------------------------------------------

ENV TOOLCHAIN_ROOT="/opt/llvm-mingw"
RUN wget https://github.com/mstorsjo/llvm-mingw/releases/download/$LLVM_MINGW_TOOLCHAIN_URI \
    -O llvm-mingw.tar.xz \
    && mkdir $TOOLCHAIN_ROOT \
    && tar -xf llvm-mingw.tar.xz --directory $TOOLCHAIN_ROOT --strip-components=1 \
    && rm llvm-mingw.tar.xz

ENV PATH=$TOOLCHAIN_ROOT/bin:$PATH \
    CC="$TOOLCHAIN_ROOT/bin/clang" \
    CXX="$TOOLCHAIN_ROOT/bin/clang++" \
    RC="$TOOLCHAIN_ROOT/bin/x86_64-w64-mingw32-windres" \
    CMAKE_TOOLCHAIN_FILE="/opt/cmake/toolchain.cmake"

COPY cmake/llvm-mingw-w64-toolchain.cmake $CMAKE_TOOLCHAIN_FILE

# -------------------------------------------------------------------------------------------------
# Install catch2, required by
# - atom_core
# -------------------------------------------------------------------------------------------------

FROM base AS catch2-builder

RUN git clone "https://github.com/catchorg/catch2.git" \
    --depth 1 --branch v$CATCH2_VERSION \
    && cd catch2 \
    && cmake -S . -B build \
    && cmake --build build \
    && cmake --install build --prefix $INSTALL_DIR

# -------------------------------------------------------------------------------------------------
# Install cpptrace, required by
# - atom_core
# -------------------------------------------------------------------------------------------------

FROM base AS cpptrace-builder

RUN git clone "https://github.com/jeremy-rifkin/cpptrace.git" \
    --depth 1 --branch v$CPPTRACE_VERSION \
    && cd cpptrace \
    && cmake -S . -B build \
    && cmake --build build \
    && cmake --install build --prefix $INSTALL_DIR

# -------------------------------------------------------------------------------------------------
# Install fmt, required by
# - atom_core
# -------------------------------------------------------------------------------------------------

FROM base AS fmt-builder

RUN git clone "https://github.com/fmtlib/fmt.git" \
    --depth 1 --branch $FMT_VERSION \
    && cd fmt \
    && cmake -S . -B build \
    && cmake --build build --target fmt \
    && cmake --install build --prefix $INSTALL_DIR

# -------------------------------------------------------------------------------------------------
# Install magic_enum, required by
# - atom_core
# -------------------------------------------------------------------------------------------------

FROM base AS magic_enum-builder

# No need to build magic_enum, it is header only
RUN git clone "https://github.com/neargye/magic_enum.git" \
    --depth 1 --branch v$MAGIC_ENUM_VERSION \
    && cd magic_enum \
    && cmake -S . -B build \
    && cmake --install build --prefix $INSTALL_DIR

# -------------------------------------------------------------------------------------------------
# Install box2d, required by
# - atom_engine
# -------------------------------------------------------------------------------------------------

FROM base AS box2d-builder

RUN git clone "https://github.com/erincatto/box2d.git" \
    --depth 1 --branch v$BOX2D_VERSION \
    && cd box2d \
    && cmake -S . -B build \
    -D BOX2D_BUILD_UNIT_TESTS=OFF \
    -D BOX2D_BUILD_TESTBED=OFF \
    -D BOX2D_BUILD_DOCS=OFF \
    -D BOX2D_USER_SETTINGS=OFF \
    -D BUILD_SHARED_LIBS=OFF \
    && cmake --build build \
    && cmake --install build --prefix $INSTALL_DIR

# -------------------------------------------------------------------------------------------------
# Install entt, required by
# - atom_engine
# -------------------------------------------------------------------------------------------------

FROM base AS entt-builder

RUN git clone "https://github.com/skypjack/entt.git" \
    --depth 1 --branch v$ENTT_VERSION \
    && cd entt \
    && cmake -S . -B build \
    && cmake --build build \
    && cmake --install build --prefix $INSTALL_DIR

# -------------------------------------------------------------------------------------------------
# Install glfw, required by
# - atom_engine
# -------------------------------------------------------------------------------------------------

FROM base AS glfw-builder

# Dependencies for wayland support
RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
    libwayland-dev \
    libxkbcommon-dev \
    wayland-protocols \
    extra-cmake-modules \
    && rm -rf /var/lib/apt/lists/*

RUN git clone "https://github.com/glfw/glfw.git" \
    --depth 1 --branch $GLFW_VERSION \
    && cd glfw \
    && cmake -S . -B build \
    && cmake --build build --target glfw \
    && cmake --install build --prefix $INSTALL_DIR

# -------------------------------------------------------------------------------------------------
# Install glm, required by
# - atom_engine
# -------------------------------------------------------------------------------------------------

FROM base AS glm-builder

RUN git clone "https://github.com/g-truc/glm.git" \
    --depth 1 --branch $GLM_VERSION \
    && cd glm \
    && cmake -S . -B build \
    -D GLM_ENABLE_CXX_20=ON \
    -D GLM_ENABLE_LANG_EXTENSIONS=ON \
    && cmake --build build \
    && cmake --install build --prefix $INSTALL_DIR

# -------------------------------------------------------------------------------------------------
# Install glslang, required by
# - atom_engine
# -------------------------------------------------------------------------------------------------

FROM base AS glslang-builder

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
    python3 \
    && rm -rf /var/lib/apt/lists/*

RUN git clone "https://github.com/KhronosGroup/glslang.git" \
    --depth 1 --branch $GLSLANG_VERSION \
    && cd glslang \
    && ./update_glslang_sources.py \
    && cmake -S . -B build \
    && cmake --build build \
    && cmake --install build --prefix $INSTALL_DIR

# -------------------------------------------------------------------------------------------------
# Install imgui, required by
# - atom_engine
# -------------------------------------------------------------------------------------------------

FROM base AS imgui-builder

RUN git clone "https://github.com/ocornut/imgui.git" $INSTALL_DIR \
    --depth 1 --branch $IMGUI_VERSION

FROM base AS vcpkg

# Set env variables
ENV VCPKG_ROOT=/opt/vcpkg
ENV PATH="$VCPKG_ROOT:$PATH"
ENV CMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"

RUN apt-get update \
    && apt-get install --yes curl zip unzip tar

# Install vcpkg
WORKDIR $VCPKG_ROOT
RUN git clone https://github.com/microsoft/vcpkg.git . \
    && ./bootstrap-vcpkg.sh

# Reset working directory
WORKDIR /app

# -------------------------------------------------------------------------------------------------
# Install zlib, required by
# - png
# - freetype
# -------------------------------------------------------------------------------------------------

FROM base AS zlib-builder

RUN git clone "https://github.com/madler/zlib.git" \
    --depth 1 --branch v$ZLIB_VERSION \
    && cd zlib \
    && cmake -S . -B build \
    -D CMAKE_INSTALL_PREFIX=$INSTALL_DIR \
    && cmake --build build \
    && cmake --install build


# -------------------------------------------------------------------------------------------------
# Install png, required by
# - freetype
# - msdf-atlas-gen
# -------------------------------------------------------------------------------------------------

FROM base AS png-builder

COPY --from=zlib-builder $INSTALL_DIR /usr/local

RUN git clone "https://github.com/pnggroup/libpng.git" \
    --depth 1 --branch v$PNG_VERSION \
    && cd libpng \
    && cmake -S . -B build \
    -D PNG_TESTS=OFF \
    && cmake --build build \
    && cmake --install build --prefix $INSTALL_DIR

# -------------------------------------------------------------------------------------------------
# Install freetype, required by
# - msdf-atlas-gen
# -------------------------------------------------------------------------------------------------

FROM base AS freetype-builder

COPY --from=png-builder $INSTALL_DIR /usr/local
COPY --from=zlib-builder $INSTALL_DIR /usr/local

RUN git clone "https://github.com/freetype/freetype.git" \
    --depth 1 --branch $FREETYPE_VERSION \
    && cd freetype \
    && cmake -S . -B build \
    && cmake --build build \
    && cmake --install build --prefix $INSTALL_DIR

# -------------------------------------------------------------------------------------------------
# Install tinyxml2, required by
# - msdf-atlas-gen
# -------------------------------------------------------------------------------------------------

FROM base AS tinyxml2-builder

RUN git clone "https://github.com/leethomason/tinyxml2.git" \
    --depth 1 --branch v$TINYXML2_VERSION \
    && cd tinyxml2 \
    && cmake -S . -B build \
    && cmake --build build \
    && cmake --install build --prefix $INSTALL_DIR

# -------------------------------------------------------------------------------------------------
# Install msdf-atlas-gen, required by
# - atom_engine
# -------------------------------------------------------------------------------------------------

FROM base AS msdf-atlas-gen-builder

COPY --from=zlib-builder $INSTALL_DIR /usr/local
COPY --from=png-builder $INSTALL_DIR /usr/local
COPY --from=freetype-builder $INSTALL_DIR /usr/local
COPY --from=tinyxml2-builder $INSTALL_DIR /usr/local

RUN git clone "https://github.com/Chlumsky/msdf-atlas-gen.git" \
    --depth 1 --branch v$MSDF_ATLAS_GEN_VERSION --recurse-submodules \
    && cd msdf-atlas-gen \
    && cmake -S . -B build \
    -D MSDF_ATLAS_USE_VCPKG=OFF \
    -D MSDF_ATLAS_USE_SKIA=OFF \
    -D MSDF_ATLAS_BUILD_STANDALONE=OFF \
    -D MSDF_ATLAS_INSTALL=ON \
    && cmake --build build \
    && cmake --install build --prefix $INSTALL_DIR

# -------------------------------------------------------------------------------------------------
# Install stb, required by
# - atom_engine
# -------------------------------------------------------------------------------------------------

FROM base AS stb-builder

RUN git clone "https://github.com/nothings/stb.git" $INSTALL_DIR \
    --depth 1 --branch $STB_VERSION

# -------------------------------------------------------------------------------------------------
# Development environment
# -------------------------------------------------------------------------------------------------

FROM base AS devenv

# -------------------------------------------------------------------------------------------------
# Install dev tools
# -------------------------------------------------------------------------------------------------

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
    clang-format-$CLANG_VERSION \
    clang-tidy-$CLANG_VERSION \
    clangd-$CLANG_VERSION \
    lldb-$CLANG_VERSION \
    cmake-format \
    doxygen \
    vim \
    && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------------------------------------------
# Install build dependencies
# -------------------------------------------------------------------------------------------------

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
    libgl1-mesa-dev \
    && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------------------------------------------
# Install dependencies
# -------------------------------------------------------------------------------------------------

COPY --from=catch2-builder $INSTALL_DIR /usr/local
COPY --from=cpptrace-builder $INSTALL_DIR /usr/local
COPY --from=fmt-builder $INSTALL_DIR /usr/local
COPY --from=magic_enum-builder $INSTALL_DIR /usr/local
COPY --from=box2d-builder $INSTALL_DIR /usr/local
COPY --from=entt-builder $INSTALL_DIR /usr/local
COPY --from=glfw-builder $INSTALL_DIR /usr/local
COPY --from=glm-builder $INSTALL_DIR /usr/local
COPY --from=glslang-builder $INSTALL_DIR /usr/local
COPY --from=imgui-builder $INSTALL_DIR $DEPS_SOURCE_DIR/imgui
COPY --from=zlib-builder $INSTALL_DIR /usr/local
COPY --from=png-builder $INSTALL_DIR /usr/local
COPY --from=freetype-builder $INSTALL_DIR /usr/local
COPY --from=tinyxml2-builder $INSTALL_DIR /usr/local
COPY --from=msdf-atlas-gen-builder $INSTALL_DIR /usr/local
COPY --from=stb-builder $INSTALL_DIR $DEPS_SOURCE_DIR/stb

ENV STB_SOURCE="$DEPS_SOURCE_DIR/stb"
ENV IMGUI_SOURCE="$DEPS_SOURCE_DIR/imgui"

# -------------------------------------------------------------------------------------------------
